spring.datasource.url=jdbc:postgresql://dpg-d850q2rbc2fs73ckpfv0-a.oregon-postgres.render.com:5432/studentdb_f8qe
spring.datasource.username=studentdb_f8qe_user
spring.datasource.password=P82zpND0cfEeypGUCGjZfdbJ2yYYKT3y

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}